import sqlite3
import json
from pathlib import Path

DB_PATH = Path("data/ecosync.db")

def get_db():
    DB_PATH.parent.mkdir(exist_ok=True)
    conn = sqlite3.connect(DB_PATH, check_same_thread=False)
    # This allows us to return rows as dictionaries automatically
    conn.row_factory = sqlite3.Row 
    return conn

def init_db():
    conn = get_db()
    cursor = conn.cursor()
    
    # Machines & LLM Limits
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS machines (
            id TEXT PRIMARY KEY,
            name TEXT,
            type TEXT,
            description TEXT,
            operating_limits JSON,
            status TEXT DEFAULT 'ONLINE'
        )
    ''')
    
    # Maintenance Schedule
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS maintenance_tasks (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            machine_id TEXT,
            task TEXT,
            interval TEXT,
            scheduled_date TEXT,
            severity TEXT DEFAULT 'INFO'
        )
    ''')
    
    # Inventory
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS spare_parts (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            machine_id TEXT,
            name TEXT,
            part_number TEXT,
            description TEXT,
            current_stock INTEGER DEFAULT 0,
            minimum_required INTEGER DEFAULT 1
        )
    ''')
    
    # Active Alerts (Generated by Pathway)
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS alerts (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            machine_id TEXT,
            level TEXT,
            message TEXT,
            timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
            acknowledged BOOLEAN DEFAULT 0
        )
    ''')
    
    # Insert a dummy machine so the UI isn't empty on first boot
    cursor.execute('''
        INSERT OR IGNORE INTO machines (id, name, type, description, operating_limits) 
        VALUES ('CNC_1', 'Haas VF-2', 'CNC Milling Machine', 'Standard 3-axis mill.', '{"temperature": {"max": 80}}')
    ''')
    
    conn.commit()
    conn.close()

# Initialize on import
init_db()

# # database/db.py
# import sqlite3
# import json
# import os
# from typing import Optional, Dict, Any

# DB_PATH = os.getenv("ECOSYNC_DB", "data/ecosync.db")
# os.makedirs(os.path.dirname(DB_PATH), exist_ok=True)

# SCHEMA = """
# PRAGMA foreign_keys = ON;

# CREATE TABLE IF NOT EXISTS manuals (
#     id INTEGER PRIMARY KEY AUTOINCREMENT,
#     machine_id TEXT NOT NULL UNIQUE,
#     pdf_path TEXT,
#     parsed_json TEXT,
#     approved INTEGER DEFAULT 0,
#     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
# );

# CREATE TABLE IF NOT EXISTS maintenance_tasks (
#     id INTEGER PRIMARY KEY AUTOINCREMENT,
#     machine_id TEXT,
#     task TEXT,
#     interval_text TEXT,
#     scheduled_date TEXT,
#     done INTEGER DEFAULT 0,
#     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
# );

# CREATE TABLE IF NOT EXISTS spare_parts (
#     id INTEGER PRIMARY KEY AUTOINCREMENT,
#     machine_id TEXT,
#     name TEXT,
#     part_number TEXT,
#     description TEXT,
#     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
# );

# CREATE TABLE IF NOT EXISTS alerts (
#     id INTEGER PRIMARY KEY AUTOINCREMENT,
#     machine_id TEXT,
#     level TEXT,
#     message TEXT,
#     meta TEXT,
#     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
# );
# """

# def get_conn():
#     conn = sqlite3.connect(DB_PATH, check_same_thread=False)
#     return conn

# def init_db():
#     conn = get_conn()
#     cur = conn.cursor()
#     for stmt in SCHEMA.strip().split(";"):
#         s = stmt.strip()
#         if s:
#             cur.execute(s)
#     conn.commit()
#     conn.close()

# def save_manual(machine_id: str, pdf_path: str, parsed_json: Dict[str, Any]) -> int:
#     conn = get_conn()
#     cur = conn.cursor()
#     pj = json.dumps(parsed_json)
#     # upsert by machine_id
#     cur.execute("SELECT id FROM manuals WHERE machine_id = ?", (machine_id,))
#     row = cur.fetchone()
#     if row:
#         cur.execute("UPDATE manuals SET pdf_path = ?, parsed_json = ?, approved = 0 WHERE machine_id = ?",
#                     (pdf_path, pj, machine_id))
#         manual_id = row[0]
#     else:
#         cur.execute("INSERT INTO manuals (machine_id, pdf_path, parsed_json) VALUES (?, ?, ?)",
#                     (machine_id, pdf_path, pj))
#         manual_id = cur.lastrowid
#     conn.commit()
#     conn.close()
#     return manual_id

# def get_manual(machine_id: str):
#     conn = get_conn()
#     cur = conn.cursor()
#     cur.execute("SELECT id, machine_id, pdf_path, parsed_json, approved, created_at FROM manuals WHERE machine_id = ?", (machine_id,))
#     row = cur.fetchone()
#     conn.close()
#     if not row:
#         return None
#     id_, mid, pdf, pj, approved, created_at = row
#     return {"id": id_, "machine_id": mid, "pdf_path": pdf, "parsed_json": json.loads(pj), "approved": bool(approved), "created_at": created_at}

# def mark_manual_approved(machine_id: str, approved: bool):
#     conn = get_conn()
#     cur = conn.cursor()
#     cur.execute("UPDATE manuals SET approved = ? WHERE machine_id = ?", (1 if approved else 0, machine_id))
#     conn.commit()
#     ok = cur.rowcount > 0
#     conn.close()
#     return ok

# def add_maintenance_task(machine_id: str, task: str, interval_text: str, scheduled_date: str = None):
#     conn = get_conn()
#     cur = conn.cursor()
#     cur.execute("INSERT INTO maintenance_tasks (machine_id, task, interval_text, scheduled_date) VALUES (?, ?, ?, ?)",
#                 (machine_id, task, interval_text, scheduled_date))
#     conn.commit()
#     conn.close()

# def get_maintenance_tasks(machine_id: str = None):
#     conn = get_conn()
#     cur = conn.cursor()
#     if machine_id:
#         cur.execute("SELECT id, machine_id, task, interval_text, scheduled_date, done, created_at FROM maintenance_tasks WHERE machine_id = ?", (machine_id,))
#     else:
#         cur.execute("SELECT id, machine_id, task, interval_text, scheduled_date, done, created_at FROM maintenance_tasks")
#     rows = cur.fetchall()
#     conn.close()
#     results = []
#     for r in rows:
#         results.append({"id": r[0], "machine_id": r[1], "task": r[2], "interval": r[3], "scheduled_date": r[4], "done": bool(r[5]), "created_at": r[6]})
#     return results

# def save_spare_parts(machine_id: str, parts_list):
#     conn = get_conn()
#     cur = conn.cursor()
#     for p in parts_list:
#         cur.execute("INSERT INTO spare_parts (machine_id, name, part_number, description) VALUES (?, ?, ?, ?)",
#                     (machine_id, p.get("name"), p.get("part_number"), p.get("description")))
#     conn.commit()
#     conn.close()

# def get_manual_parsed_thresholds(machine_id: str):
#     """Return parsed numeric thresholds if present (temp min/max, noise) to be used by alerting pipeline"""
#     m = get_manual(machine_id)
#     if not m:
#         return None
#     parsed = m.get("parsed_json", {})
#     ot = parsed.get("operating_temperature", {}) or {}
#     sound = parsed.get("sound_level_db", None)
#     return {
#         "temp_min": ot.get("min"),
#         "temp_max": ot.get("max"),
#         "temp_unit": ot.get("unit"),
#         "sound_db": sound
#     }

# def save_alert(machine_id: str, level: str, message: str, meta: dict = None):
#     conn = get_conn()
#     cur = conn.cursor()
#     cur.execute("INSERT INTO alerts (machine_id, level, message, meta) VALUES (?, ?, ?, ?)",
#                 (machine_id, level, message, json.dumps(meta or {})))
#     conn.commit()
#     conn.close()