import sqlite3
import json
from pathlib import Path

DB_PATH = Path("data/ecosync.db")

def get_db():
    DB_PATH.parent.mkdir(exist_ok=True)
    conn = sqlite3.connect(DB_PATH, check_same_thread=False)
    # This allows us to return rows as dictionaries automatically
    conn.row_factory = sqlite3.Row 
    return conn

def init_db():
    conn = get_db()
    cursor = conn.cursor()
    
    # Machines & LLM Limits
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS machines (
            id TEXT PRIMARY KEY,
            name TEXT,
            type TEXT,
            description TEXT,
            operating_limits JSON,
            status TEXT DEFAULT 'ONLINE'
        )
    ''')
    
    # Maintenance Schedule
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS maintenance_tasks (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            machine_id TEXT,
            task TEXT,
            interval TEXT,
            scheduled_date TEXT,
            severity TEXT DEFAULT 'INFO'
        )
    ''')
    
    # Inventory
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS spare_parts (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            machine_id TEXT,
            name TEXT,
            part_number TEXT,
            description TEXT,
            current_stock INTEGER DEFAULT 0,
            minimum_required INTEGER DEFAULT 1
        )
    ''')
    
    # Active Alerts (Generated by Pathway)
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS alerts (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            machine_id TEXT,
            level TEXT,
            message TEXT,
            timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
            acknowledged BOOLEAN DEFAULT 0
        )
    ''')
    
    # Insert a dummy machine so the UI isn't empty on first boot
    cursor.execute('''
        INSERT OR IGNORE INTO machines (id, name, type, description, operating_limits) 
        VALUES ('CNC_1', 'Haas VF-2', 'CNC Milling Machine', 'Standard 3-axis mill.', '{"temperature": {"max": 80}}')
    ''')
    
    conn.commit()
    conn.close()

# Initialize on import
init_db()